In [14]:
import numpy as np
import pandas as pd

In [15]:
data=pd.read_csv('synthetic_logs.csv')

In [16]:
data.head()

,timestamp,source,log_message,target_label,complexity,Unnamed: 5,Unnamed: 6
0,timestamp,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,NaN,NaN
1,timestamp,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,NaN,NaN
2,timestamp,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,NaN,NaN
3,timestamp,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,NaN,NaN
4,timestamp,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,NaN,NaN

In [17]:
data['complexity'].unique()

<StringArray>
['bert', 'regex', 'llm']
Length: 3, dtype: str

In [18]:
data['source'].unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [19]:
data['log_message'].head(30)

0     nova.osapi_compute.wsgi.server [req-b9718cd8-f...
1        Email service experiencing issues with sending
2             Unauthorized access to data was attempted
3     nova.osapi_compute.wsgi.server [req-4895c258-b...
4     nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...
5     nova.osapi_compute.wsgi.server [req-f0bffbc3-5...
6             Shard 6 replication task ended in failure
7     File data_6169.csv uploaded successfully by us...
8     nova.compute.claims [req-a07ac654-8e81-416d-bf...
9     nova.osapi_compute.wsgi.server [req-2bf7cfee-a...
10             Email server encountered a sending fault
11      Critical system unit error: unit ID Component55
12    nova.osapi_compute.wsgi.server [req-d4f8d0c2-4...
13    Multiple bad login attempts detected on user 8...
14    File data_3847.csv uploaded successfully by us...
15                       Backup completed successfully.
16    nova.osapi_compute.wsgi.server [req-6fe0e366-f...
17    nova.osapi_compute.wsgi.server [req-5f1c2027-e...
18             Account with ID 5351 created by User634.
19    nova.osapi_compute.wsgi.server [req-945d1f31-a...
20    nova.osapi_compute.wsgi.server [req-033d97b9-6...
21    nova.osapi_compute.wsgi.server [req-75bc6269-8...
22    nova.compute.resource_tracker [req-addc1839-2e...
23    nova.osapi_compute.wsgi.server [req-077c3c87-b...
24    nova.osapi_compute.wsgi.server [req-4e83daf7-a...
25    nova.osapi_compute.wsgi.server [req-bfce366e-9...
26    nova.compute.claims [req-d6986b54-3735-4a42-90...
27                             User User685 logged out.
28    nova.osapi_compute.wsgi.server [req-5e6e042b-f...
29    Alert: brute force login attempt from 192.168....
Name: log_message, dtype: str

In [20]:
data['timestamp'].head(10)

0    timestamp
1    timestamp
2    timestamp
3    timestamp
4    timestamp
5    timestamp
6    timestamp
7    timestamp
8    timestamp
9    timestamp
Name: timestamp, dtype: str

1-timestamp sahi kro \
2- regex pattern\
3-bert classification\
4-llm classification

In [21]:
data['target_label'].unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [22]:
data[data['target_label'] == 'HTTP Status']

,timestamp,source,log_message,target_label,complexity,Unnamed: 5,Unnamed: 6
0,timestamp,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,NaN,NaN
3,timestamp,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,NaN,NaN
4,timestamp,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,NaN,NaN
5,timestamp,ModernHR,nova.osapi_compute.wsgi.server [req-f0bffbc3-5...,HTTP Status,bert,NaN,NaN
9,timestamp,ModernHR,nova.osapi_compute.wsgi.server [req-2bf7cfee-a...,HTTP Status,bert,NaN,NaN
...,...,...,...,...,...,...,...
2399,08-03-2025 06:23,ThirdPartyAPI,nova.metadata.wsgi.server [req-ba29717b-249a-4...,HTTP Status,bert,NaN,NaN
2401,05-12-2025 15:51,ModernCRM,nova.osapi_compute.wsgi.server [req-4bdf00b0-3...,HTTP Status,bert,NaN,NaN
2404,18-09-2025 02:18,ThirdPartyAPI,nova.osapi_compute.wsgi.server [req-2c9c783f-3...,HTTP Status,bert,NaN,NaN
2405,13-08-2025 07:29,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,NaN,NaN
2407,03-08-2025 03:07,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,NaN,NaN

In [23]:
reg_data=data[data['complexity']=='regex']

In [24]:
reg_data['target_label'].unique()

<StringArray>
['System Notification', 'User Action']
Length: 2, dtype: str

In [25]:
data[data['target_label'] == 'HTTP Status'].iloc[0]['log_message']

'nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118'

In [35]:
reg_data[reg_data['target_label'] == 'System Notification']

,timestamp,source,log_message,target_label,complexity,Unnamed: 5,Unnamed: 6
7,timestamp,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,regex,NaN,NaN
14,timestamp,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,regex,NaN,NaN
15,timestamp,ModernCRM,Backup completed successfully.,System Notification,regex,NaN,NaN
30,4/26/2025 7:54,AnalyticsEngine,Backup started at 2025-05-14 07:06:55.,System Notification,regex,NaN,NaN
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification,regex,NaN,NaN
...,...,...,...,...,...,...,...
2376,6/27/2025 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,regex,NaN,NaN
2381,09-05-2025 06:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex,NaN,NaN
2394,04-03-2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,regex,NaN,NaN
2395,05-02-2025 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,regex,NaN,NaN
2403,10-01-2025 01:31,ModernCRM,Backup completed successfully.,System Notification,regex,NaN,NaN

In [44]:
reg_data[~reg_data["log_message"].str.contains("backup", case=False, na=False)]

,timestamp,source,log_message,target_label,complexity,Unnamed: 5,Unnamed: 6
7,timestamp,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,regex,NaN,NaN
14,timestamp,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,regex,NaN,NaN
18,timestamp,ModernCRM,Account with ID 5351 created by User634.,User Action,regex,NaN,NaN
27,timestamp,ThirdPartyAPI,User User685 logged out.,User Action,regex,NaN,NaN
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification,regex,NaN,NaN
...,...,...,...,...,...,...,...
2364,04-05-2025 10:28,ModernCRM,System updated to version 2.7.8.,System Notification,regex,NaN,NaN
2368,12/13/2025 20:04,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex,NaN,NaN
2376,6/27/2025 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,regex,NaN,NaN
2381,09-05-2025 06:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex,NaN,NaN
2394,04-03-2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,regex,NaN,NaN